<x-layouts.app title="البيانات الأساسية">
<main dir="rtl" class="mx-auto max-w-7xl space-y-6 px-6 py-8">
<section><h1 class="text-3xl font-bold">البيانات الأساسية</h1><p class="mt-2 text-sm text-gray-600">المركبات والبرادات وأصحاب العهد ومعايير الأقفاص والمنتجات النهائية.</p></section>
@if($errors->any())<div class="rounded-lg bg-red-50 p-4 text-sm text-red-800">@foreach($errors->all() as $error)<div>{{ $error }}</div>@endforeach</div>@endif
<div class="grid gap-6 lg:grid-cols-2">
<section class="rounded-2xl border bg-white p-6"><h2 class="text-xl font-bold">المركبات</h2><form method="POST" action="{{ route('master-data.vehicles.store') }}" class="mt-4 grid gap-3 sm:grid-cols-2">@csrf<input name="plate_number" required placeholder="رقم اللوحة" class="rounded-lg border-gray-300"><input name="type" placeholder="النوع" class="rounded-lg border-gray-300"><input name="driver_name" placeholder="اسم السائق" class="rounded-lg border-gray-300"><input name="driver_phone" placeholder="هاتف السائق" class="rounded-lg border-gray-300"><input name="notes" placeholder="ملاحظات" class="rounded-lg border-gray-300 sm:col-span-2"><button class="rounded-lg bg-gray-900 px-4 py-2 text-white sm:col-span-2">إضافة مركبة</button></form><div class="mt-4 space-y-2">@foreach($vehicles as $v)<div class="rounded-lg border p-3"><b>{{ $v->plate_number }}</b> — {{ $v->type ?: 'بدون نوع' }} — {{ $v->driver_name ?: 'بدون سائق' }}</div>@endforeach</div></section>
<section class="rounded-2xl border bg-white p-6"><h2 class="text-xl font-bold">البرادات</h2><form method="POST" action="{{ route('master-data.cold-stores.store') }}" class="mt-4 grid gap-3 sm:grid-cols-2">@csrf<input name="name" required placeholder="اسم البراد" class="rounded-lg border-gray-300"><input name="code" required placeholder="الكود" class="rounded-lg border-gray-300"><select name="crate_standard_id" class="rounded-lg border-gray-300 sm:col-span-2"><option value="">بدون معيار</option>@foreach($crateStandards->where('is_active',true) as $s)<option value="{{ $s->id }}">{{ $s->name }}</option>@endforeach</select><button class="rounded-lg bg-gray-900 px-4 py-2 text-white sm:col-span-2">إضافة براد</button></form><div class="mt-4 space-y-2">@foreach($coldStores as $c)<div class="flex items-center justify-between rounded-lg border p-3"><span><b>{{ $c->name }}</b> — {{ $c->code }} — {{ $c->current_crates_count }} قفص</span>@if($c->is_active)<form method="POST" action="{{ route('master-data.cold-stores.close',$c) }}">@csrf<button class="rounded border px-3 py-1 text-red-700">إغلاق</button></form>@else<span class="text-sm text-gray-500">مغلق</span>@endif</div>@endforeach</div></section>
<section class="rounded-2xl border bg-white p-6"><h2 class="text-xl font-bold">أصحاب العهد</h2><form method="POST" action="{{ route('master-data.custodians.store') }}" class="mt-4 grid gap-3 sm:grid-cols-2">@csrf<input name="name" required placeholder="الاسم" class="rounded-lg border-gray-300"><input name="phone" placeholder="الهاتف" class="rounded-lg border-gray-300"><button class="rounded-lg bg-gray-900 px-4 py-2 text-white sm:col-span-2">إضافة</button></form><div class="mt-4 space-y-2">@foreach($custodians as $c)<div class="flex items-center justify-between rounded-lg border p-3"><span>{{ $c->name }} — {{ $c->is_active ? 'نشط' : 'معطل' }}</span><form method="POST" action="{{ route('master-data.custodians.toggle',$c) }}">@csrf<button class="rounded border px-3 py-1">{{ $c->is_active ? 'تعطيل' : 'تفعيل' }}</button></form></div>@endforeach</div></section>
<section class="rounded-2xl border bg-white p-6"><h2 class="text-xl font-bold">معايير الأقفاص</h2><form method="POST" action="{{ route('master-data.crate-standards.store') }}" class="mt-4 grid gap-3 sm:grid-cols-2">@csrf<input name="name" required placeholder="اسم المعيار" class="rounded-lg border-gray-300 sm:col-span-2"><input name="gross_weight_kg" type="number" step="0.001" min="0.001" required placeholder="إجمالي كجم" class="rounded-lg border-gray-300"><input name="tare_weight_kg" type="number" step="0.001" min="0" required placeholder="تارة كجم" class="rounded-lg border-gray-300"><button class="rounded-lg bg-gray-900 px-4 py-2 text-white sm:col-span-2">إضافة معيار</button></form><div class="mt-4 space-y-2">@foreach($crateStandards as $s)<div class="flex items-center justify-between rounded-lg border p-3"><span>{{ $s->name }} — صافي {{ number_format($s->netWeightKg(),3) }} كجم</span><form method="POST" action="{{ route('master-data.crate-standards.toggle',$s) }}">@csrf<button class="rounded border px-3 py-1">{{ $s->is_active ? 'تعطيل' : 'تفعيل' }}</button></form></div>@endforeach</div></section>
<section class="rounded-2xl border bg-white p-6 lg:col-span-2"><h2 class="text-xl font-bold">المنتجات النهائية</h2><form method="POST" action="{{ route('master-data.products.store') }}" class="mt-4 grid gap-3 sm:grid-cols-4">@csrf<input name="name" required placeholder="اسم المنتج" class="rounded-lg border-gray-300"><input name="code" required placeholder="الكود" class="rounded-lg border-gray-300"><input name="type" required placeholder="النوع" class="rounded-lg border-gray-300"><input name="unit" required value="kg" placeholder="الوحدة" class="rounded-lg border-gray-300"><button class="rounded-lg bg-gray-900 px-4 py-2 text-white sm:col-span-4">إضافة منتج</button></form><div class="mt-4 space-y-2">@foreach($products as $p)<div class="flex items-center justify-between rounded-lg border p-3"><span>{{ $p->name }} — {{ $p->code }} — {{ number_format((float)($p->stock?->quantity ?? 0),3) }} {{ $p->unit }}</span><form method="POST" action="{{ route('master-data.products.toggle',$p) }}">@csrf<button class="rounded border px-3 py-1">{{ $p->is_active ? 'تعطيل' : 'تفعيل' }}</button></form></div>@endforeach</div></section>
</div></main></x-layouts.app>
